sile.tests: fix the eval
Without the chnage the eval fails on `master` as:

    $ nix build --no-link -f. sile.tests
    error:
       … while calling the 'derivationStrict' builtin
         at «nix-internal»/derivation-internal.nix:37:12:
           36|
           37|   strict = derivationStrict drvAttrs;
             |            ^
           38|

       … while evaluating derivation 'sile-test'
         whose name attribute is located at pkgs/stdenv/generic/make-derivation.nix:536:13

       … while evaluating attribute 'FONTCONFIG_FILE' of derivation 'sile-test'
         at pkgs/by-name/si/sile/package.nix:164:32:
          163|           ];
          164|           inherit (finalAttrs) FONTCONFIG_FILE;
             |                                ^
          165|         }

       error: attribute 'FONTCONFIG_FILE' missing
       at pkgs/by-name/si/sile/package.nix:164:32:
          163|           ];
          164|           inherit (finalAttrs) FONTCONFIG_FILE;
             |                                ^
          165|         }

Co-authored-by: Jo <jopejoe1@missing.ninja>