nixos/frigate: fix HTTP method allowed for WebRTC API
The Frigate Home Assistant integration POSTs to this endpoint to start a
WebRTC session[1], so the allowed method should be POST, not GET. The
current configuration causes an HTTP 403 error when viewing a camera
stream in Home Assistant:

```
aiohttp.client_exceptions.ContentTypeError: 403, message='Attempt to decode JSON with unexpected mimetype: text/html', url='https://$HOSTNAME/api/go2rtc/webrtc?src=$CAMERA'
```

[1]: https://github.com/blakeblackshear/frigate-hass-integration/blob/v5.14.1/custom_components/frigate/camera.py#L575